### ISSUE TITLE
encode/decode methods

### ISSUE THREAD

**Issue by ggl** [ingydotnet/tiny-yaml-pm#3]
Can you provide encode/decode methods (not functions) as an alias to Load/Dump in the OO API so that we could use this as a generic serializer without too much boilerplate? Most Perl searializers (JSON, Sereal, etc.) use encode/decode methods. Or just rename the load and _dump_string methods that you are using internally. There would also be no object instantiation overhead.

**Comment by ingydotnet** [comment]
encode and decode are the wrong terms. They mean to turn one string into another. Like with HTML. 

load/dump have been in use much longer than JSON has existed. In Ruby, for instance, JSON uses load/dump. They mean a transformation between string and object, and they actually involve a stack of transforms that all have names. See http://yaml.org/spec/1.2/spec.html#id2762107

FWIW, freeze/thaw are appropriate terms that have a lot of prior art. But YAML has been using load/dump since 2001.

**Comment by ggl** [comment]
Well they do turn one data structure (perl) into another (yaml, json, sereal, etc.), both of which can be represented as strings. Also the term seems generic enough and correct.

encode
     1. <algorithm, hardware> To convert {data} or some physical
     quantity into a given format.  E.g. {uuencode}.
     See also {encoder}.
     2. <cryptography> To encrypt, to perform {encryption}.

The reasoning for this is that these methods became common enough for most Perl serializers. FEEZE/THAW is incresingly used for generic object serialization (JSON::XS, Sereal, CBOR::XS), see:

https://metacpan.org/pod/Types::Serialiser

**Comment by ingydotnet** [comment]
You should join IRC #yaml on irc.perl.org if you want to discuss it, but I'm
quite solid that load/dump are the correct terms. They are also the API shared
across all YAML processors in all languages.

Sereal is very new and chose the wrong terms, IMO. They probably took them from
JSON without much thought. Those terms apply well to string->string operations,
but not to serialization which is a multilevel thing.

Load is the unbrella term for Read->Lex->Parse->Compose->Construct and Dump has
the same stack in reverse.

Also this is the wrong repo to discuss this. Tiny::YAML is just a module to
work on the replacement for YAML::Tiny and YAML.pm.

Closing this issue, but feel free to find me on IRC if you want to discuss it.
